# Generated by Django 3.0.7 on 2021-03-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank='False', default='', max_length=50, unique='True')),
                ('firstname', models.CharField(blank='False', default='', max_length=50)),
                ('lastname', models.CharField(blank='False', default='', max_length=50)),
                ('password', models.CharField(blank='False', default='', max_length=50)),
                ('address', models.CharField(blank='False', default='', max_length=50)),
                ('dob', models.DateField(blank='False', default='')),
                ('company', models.CharField(blank='False', default='', max_length=50)),
                ('mobile', models.CharField(blank='False', default='', max_length=10)),
                ('city', models.CharField(blank='False', default='', max_length=50)),
            ],
        ),
    ]
